name: Vision CI/CD Main Branch

on:
  push:
    branches:
      - cicd

jobs:
  build-and-test:
    name: Vision / Build and Test 
    runs-on: ubuntu-20.04
    steps:    
    - uses: actions/checkout@v3

  build-and-push-staging-docker-image:
    name: Vision / Build and Push Staging Docker Image 
    environment: staging
    runs-on: ubuntu-20.04
    steps:    
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push vision-api for Staging
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vision-api:${{ github.sha }}-staging

    - name: Build and push vision-cleanup for Staging
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile-cleanup
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vision-cleanup:${{ github.sha }}-staging

  deploy-staging:
    name: Vision / Deploy to Staging
    environment: staging
    needs: [build-and-test, build-and-push-staging-docker-image]
    runs-on: ubuntu-20.04
    steps:    
    - name: Deploy to Staging
      uses: docker/setup-buildx-action@v3

  tag-and-push-production-docker-image:
    name: Vision / Tag and Push Production Docker Image 
    environment: production
    needs: [deploy-staging]
    runs-on: ubuntu-20.04
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Tag and push vision-api for Production
      uses: docker/setup-buildx-action@v3

    - name: Tag and push vision-cleanup for Production
      uses: docker/setup-buildx-action@v3

  deploy-staging:
    name: Vision / Deploy to Production
    environment: production
    needs: [tag-and-push-production-docker-image]
    runs-on: ubuntu-20.04
    - name: Deploy to Production
      uses: docker/setup-buildx-action@v3
