name: Vision CI/CD Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build/Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

  build-and-push-staging-docker-image:
    name: Build/Push Staging Docker Image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build/Push staging vision-api
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vision-api:${{ github.sha }}

    - name: Build/Push staging vision-cleanup
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile-cleanup
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vision-cleanup:${{ github.sha }}
