name: Vision CI/CD Dev Branch

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-and-test:
    name: Build/Test 
    runs-on: ubuntu-20.04
    steps:    
    - uses: actions/checkout@v4

  build-and-push-dev-docker-image:
    name: Build/Push Dev Docker Image 
    runs-on: ubuntu-20.04
    steps:    
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build/Push dev vision-api
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vision-api:${{ github.ref_name }}

    - name: Build/Push dev vision-cleanup
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile-cleanup
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vision-cleanup:${{ github.ref_name }}
